<?xml version="1.0"?>
<robot name="robot_3d"
  xmlns:xacro="http://www.ros.org/wiki/xacro"
  xmlns:gz="http://gazebosim.org/schema">

  <xacro:property name="M_PI" value="3.1415926535897931" />

  <xacro:arg name="robot_name" default="robot_3d"/>
  <xacro:arg name="prefix" default=""/>
  <xacro:arg name="use_gazebo" default="false"/>

  <xacro:include filename="$(find camera_description)/urdf/sensors/rgbd_camera.urdf.xacro"/>
  <xacro:include filename="$(find camera_description)/urdf/control/camera_control.gazebo"/>

  <!-- Define box dimensions as variables -->
  <xacro:property name="box_length" value="0.1" />
  <xacro:property name="box_width" value="0.15" />
  <xacro:property name="box_height" value="0.05" />

  <!-- Define camera placement properties -->
  <xacro:property name="camera_z_offset" value="0" />
  <xacro:property name="camera_x_offset" value="${box_length/2+0.02}" />
  <xacro:property name="camera_y_offset" value="0" />
  <!-- add 2cm offset form camera origin -->
  <xacro:property name="camera_rx_offset" value="0" />
  <xacro:property name="camera_ry_offset" value="0" />
  <xacro:property name="camera_rz_offset" value="${0}" />
  
  <xacro:rgbd_camera prefix="$(arg prefix)" parent="dummy_link" mass = "0.01" camera_name="camera" xyz_offset="${camera_x_offset} ${camera_y_offset} ${camera_z_offset}" rpy_offset="${camera_rx_offset} ${camera_ry_offset} ${camera_rz_offset}" material_color="0.5 0.2 0.2 1" />



  <!-- Define the new root link (dummy_link) -->
  <link name="dummy_link">
    <gravity>0</gravity>
    <visual>
      <geometry>
        <box size="0.001 0.001 0.001"/>
      </geometry>
      <material name="transparent">
        <color rgba="0 0 0 0"/>
        <!-- Making it invisible -->
      </material>
    </visual>
  </link>

  

   <!--<link name="base_link">
    <gravity>0</gravity>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1.0"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
    </inertial>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${box_length} ${box_width} ${box_height}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${box_length} ${box_width} ${box_height}"/>
      </geometry>
      <material name="red">
        <color rgba="1 0.2 0.2 1.0"/>
      </material>
    </visual>
  </link>
  
  <!~~> Fixed joint connecting dummy_link to base_link ~~>
  <joint name="dummy_to_base" type="fixed">
    <gravity>0</gravity>
    <parent link="dummy_link"/>
    <child link="base_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>-->
<!--


  <gazebo reference="base_link">
    <gravity>0</gravity>
  </gazebo>-->


  <gazebo reference="camera_link">
    <material>Gazebo/Blue</material>
  </gazebo>


</robot>