pose_estimation_pcl:
  ros__parameters:
    # General Parameters
    use_sim_time: true
    frame_id: "base_link"
    processing_period_ms: 100
    use_goicp : false
    goicp_debug : false
    save_debug_clouds : true

    # ICP parameters
    gicp_fitness_threshold: 0.05
    gicp_max_iterations: 100

    # Point Cloud Processing Parameters
    voxel_size: 0.2
    save_debug_clouds: true
    object_frame: "docking_st"
    
    # Clustering Parameters
    cluster_tolerance: 0.03 #in meters, default is 0.03
    min_cluster_size: 250 #250
    max_cluster_size: 75000 #50000
    
    # Plane Segmentation Parameters
    plane_distance_threshold: 0.01
    max_plane_iterations: 100
    min_plane_points: 800
    max_planes: 3