pose_estimation_pcl:
  ros__parameters:
    general:
      processing_period_ms: 50
      goicp_debug : true
      save_debug_clouds : true
      object_frame: "custom_docking_st"
      debug_grapple : false
      save_to_pcd_ : false
      suffix_name_pcd : "_center_test"
      debug_time : false

    preprocess:
      voxel_size: 0.012 # 0.012 for grapple, 0.01 for docking
      max_depth: 2.0 # in meter
      cluster_pc: true


    gen_icp:
      fitness_threshold: 5e-2 # good threshold for the fitness score is 3e-4 for grapple, 1.5e-3 for docking
      max_iteration : 75
      transformation_epsilon: 5e-3 # 1e-6
      max_correspondence_distance: 0.08 # 0.1 m default
      fitness_epsilon: 5e-4 # 5e-4
      ransac_threshold: 0.1

    go_icp:
      use_goicp : false
      mse_threshold: 5e-4 # 5e-4 for grapple, 4e-4 for docking
      dt_size: 50 # 25 for grapple, 50 for docking
      dt_expandFactor: 3.0 # lowering will increase orientation accuracy a lot, 4.0 for grapple

    clustering:
      cluster_tolerance: 0.03 #in meters, default is 0.03
      min_cluster_size: 150 #250
      max_cluster_size: 75000 #50000
      

    3d_decriptors:
      visualize_normals: false
      normal_radius: 0.1 # the highger the more neighbor to consider, improving the normal vector
      fpfh_radius: 0.07 # the highger the more neighbor to consider, improving the descriptor
      similarity_threshold : 0.5 #0.5
    
    plane_detection:
      distance_threshold: 0.02
      max_iterations: 100
      min_plane_points: 500
      max_planes: 3