pose_estimation_pcl:
  ros__parameters:
    general:
      camera_frame : "camera_link" # "camera_link" for sitl, "zed2i_left_camera_frame" for hardware
      pcd_dir: "/home/tafarrel/o3d_logs" #"/home/tafarrel/o3d_logs" for sitl, "/home/px4_space/o3d_files" for hardware
      pc_topic : "/camera/points" #"/zed/zed_node/point_cloud/cloud_registered"
      processing_period_ms: 100 #50
      goicp_debug : true
      save_debug_clouds : true
      object_frame: "custom_docking_st"
      debug_grapple : false
      save_to_pcd_ : false
      suffix_name_pcd : "_center_test"
      debug_time : false

    preprocess:
      voxel_size: 0.012 # 0.012 for grapple, 0.01 for docking
      max_depth: 3.0 # in meter
      cluster_pc: false


    gen_icp:
      fitness_threshold: 5e-2 # good threshold for the fitness score is 3e-4 for grapple, 5e-2 for docking
      max_iteration : 150 
      transformation_epsilon: 5e-3 # 1e-6 for grapple, 5e-3 for docking
      max_correspondence_distance: 0.4 # 0.1 m default, 0.3 for custom_docking (for rotational motion error)
      euclidean_fitness_epsilon: 5e-4 # 5e-4
      ransac_threshold: 0.1

    go_icp:
      use_goicp : false
      mse_threshold: 6e-4 # 5e-4 for grapple, 4e-4 for docking
      dt_size: 50 # 25 for grapple, 50 for docking
      dt_expandFactor: 3.0 # lowering will increase orientation accuracy a lot, 4.0 for grapple, 3.0 for docking
      trim_fraction: 0.25 # 0.55 for experiment, 0.0 for no trimming
      
    clustering:
      cluster_tolerance: 0.03 #in meters, default is 0.03
      min_cluster_size: 150 #250
      max_cluster_size: 75000 #50000

      

    3d_decriptors:
      visualize_normals: false
      normal_radius: 0.1 # the highger the more neighbor to consider, improving the normal vector
      fpfh_radius: 0.07 # the highger the more neighbor to consider, improving the descriptor
      similarity_threshold : 0.5 #0.5

    super4pcs:
      delta: 0.008 # accuracy parameter, adjust based on point cloud resolution
      overlap: 0.8 # expected overlap (0-1, adjust)
      max_iterations: 250 # maximum iterations (can adjust)
    
    plane_detection:
      distance_threshold: 0.02
      max_iterations: 100
      min_plane_points: 1000
      max_planes: 3