pose_estimation_pcl:
  ros__parameters:
    general:
      processing_period_ms: 100
      goicp_debug : false
      save_debug_clouds : true
      voxel_size: 0.012
      object_frame: "grapple"
      debug_grapple : false
      save_to_pcd_ : false
      suffix_name_pcd : "_center_test"

    gen_icp:
      fitness_threshold: 1.5e-3 # good threshold for the fitness score is 3e-4
      max_iteration : 75
      transformation_epsilon: 5e-3 # 1e-6
      max_correspondence_distance: 0.08 # 0.1 m default
      fitness_epsilon: 5e-4 # 5e-4
      ransac_threshold: 0.1

    go_icp:
      use_goicp : true
      mse_threshold: 5e-4 # 9e-4
      dt_size: 25
      dt_expandFactor: 4.0 # lowering will increase orientation accuracy a lot

    clustering:
      cluster_tolerance: 0.03 #in meters, default is 0.03
      min_cluster_size: 150 #250
      max_cluster_size: 75000 #50000

    3d_decriptors:
      visualize_normals: false
      normal_radius: 0.1 # the highger the more neighbor to consider, improving the normal vector
      fpfh_radius: 0.07 # the highger the more neighbor to consider, improving the descriptor
      similarity_threshold : 0.5 #0.5
    
    plane_detection:
      plane_distance_threshold: 0.02
      max_plane_iterations: 100
      min_plane_points: 500
      max_planes: 3